import React from 'react'

export const Content = () => {
  return (
    <div className="content"><div className="blogpost"> <b>Under construction!</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Placerat in egestas erat imperdiet sed. Amet dictum sit amet justo donec. Ultricies leo integer malesuada nunc vel risus commodo viverra. Enim neque volutpat ac tincidunt vitae. Mi eget mauris pharetra et ultrices neque ornare. Nam at lectus urna duis convallis convallis tellus. Curabitur vitae nunc sed velit dignissim sodales ut. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Diam sit amet nisl suscipit adipiscing.
<p></p>
    Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Aliquam ultrices sagittis orci a scelerisque. Dui id ornare arcu odio. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. At consectetur lorem donec massa sapien faucibus. Viverra suspendisse potenti nullam ac tortor vitae. Mattis vulputate enim nulla aliquet porttitor. Quis auctor elit sed vulputate mi sit amet mauris. Tempor orci eu lobortis elementum nibh tellus. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Condimentum id venenatis a condimentum vitae sapien pellentesque. Sed tempus urna et pharetra pharetra.
    <p></p>  
    Nunc consequat interdum varius sit amet mattis. Tellus orci ac auctor augue mauris. Porttitor eget dolor morbi non arcu risus quis. Quis blandit turpis cursus in hac habitasse platea dictumst. Habitant morbi tristique senectus et netus. Pulvinar elementum integer enim neque. Pellentesque id nibh tortor id aliquet. Velit dignissim sodales ut eu sem integer vitae justo eget. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Lectus mauris ultrices eros in. Tortor aliquam nulla facilisi cras fermentum odio eu. Libero enim sed faucibus turpis in eu mi. Augue ut lectus arcu bibendum at varius vel pharetra. Lacus sed viverra tellus in. Quam viverra orci sagittis eu volutpat odio facilisis. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Odio euismod lacinia at quis risus sed vulputate. Ultrices dui sapien eget mi proin sed. Ultricies leo integer malesuada nunc vel risus commodo.
    <p></p>
    Suspendisse in est ante in. Sed egestas egestas fringilla phasellus faucibus scelerisque. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Aliquam eleifend mi in nulla. Ac turpis egestas sed tempus urna et pharetra pharetra. Elit ut aliquam purus sit amet. Leo in vitae turpis massa. Sapien pellentesque habitant morbi tristique senectus et netus et. Dolor purus non enim praesent elementum facilisis leo vel. Nibh sit amet commodo nulla. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh.
    <p></p>
    Neque volutpat ac tincidunt vitae semper quis lectus nulla. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Amet justo donec enim diam vulputate. Ipsum faucibus vitae aliquet nec ullamcorper. Habitant morbi tristique senectus et netus et malesuada fames ac. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Vel quam elementum pulvinar etiam non quam lacus. Nec ultrices dui sapien eget mi proin. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Ullamcorper morbi tincidunt ornare massa eget egestas.</div>
    </div>
  )
}
